### ISSUE TITLE
how to get the watermark from a image?

### ISSUE THREAD

**Issue by jinganglang567** [bsmhmmlf/Gaussian-Shading#1]
Sorry to bother you doctor,if i want to visualize the watermark before generate the image and after generate the image

**Comment by bsmhmmlf** [comment]
In Gaussian Shading, the watermark information is directly mapped to latent representations. If you want to visualize the watermark, you can inspect the variables `init_latents_w` and `reversed_latents_w` in the code for visualization.

> Sorry to bother you doctor,if i want to visualize the watermark before generate the image and after generate the image
