### ISSUE TITLE
Parameter settings  for detection scenario

### ISSUE THREAD

**Issue by xinxinzi8** [bsmhmmlf/Gaussian-Shading#2]
Hi author, could you please tell me how to set the parameter when running the experiment for detection scenario? Should I set the user_number =1 with channel_copy=1  and hw_copy =8 ? Thank you!

**Comment by bsmhmmlf** [comment]
@xinxinzi8 If you want to get the results of the detection scenario, you need to set `channel_copy=1` and `hw_copy =8`, and then focus on the `tpr_detection` . `user_number` is fine to set to whatever you want because it only affects `tpr_traceability`, which is a metric for the traceability scenario that has nothing to do with detection.

**Comment by xinxinzi8** [comment]
Thank you very much!

**Comment by xinxinzi8** [comment]
Hello, I have another question about this line `self.tau_onebit = (i+1) / self.marklength` in watermark.py. Why`  i+1 ` is used when calculate tau_onebit and tau_bits? According to the formula of FPR($\tau$) = B($\tau$ + 1, k - $\tau$, 0.5), I think ` i` means $\tau$ here. Thank you very much!

**Comment by bsmhmmlf** [comment]
> Hello, I have another question about this line `self.tau_onebit = (i+1) / self.marklength` in watermark.py. Why`i+1` is used when calculate tau_onebit and tau_bits? According to the formula of FPR(τ) = B(τ + 1, k - τ, 0.5), I think `i` means τ here. Thank you very much!

@xinxinzi8 Thank you for pointing out this error! Here it should be` self.tau_onebit = i / self.marklength` and ` self.tau_bits = i / self.marklength` . If the original code is followed, the theoretical FPR should be smaller, and the conditions are more stringent for calculating the TPR. We will fix this error as soon as possible！
